## Singular Matrix Decomposition

Applying the SVD to a matrix is like looking inside it with X_Ray vision.

SVD is used to reduce dimension of 2D matrices

It is one of the most widely used Unsupervised learning algorithms that is at that center of many recommandation and Dimentionality reduction system

In [38]:
import numpy as np

In [94]:
a = np.array([[5,5],
             [-1,7]])

The idea of SVD's formula come from eigen vectors. I'm not going into depth of full derivation of formula but in simple manner SVD reduces a matrix $A$ into 3 sub matrices where $U$ is columns space of $A$, $epsilon$ is singular value space of also known as **eign values** of each dimensions $A$, and $V$ is row space of $A$

$U$ and $V$ are orthogonal vectors and also unit vectors with respect to each dimensions

In [95]:
# Now, we have a matrix'A' and we need to reduce in three parts
# formula is A = U * ep * V
# we can also right
#  A.(A.T) => (U * ep * V).(U * ep * V).T  => U.(ep).(U.T)  ---- 1
#  (A.T).A => (U * ep * V).T .(U * ep * V) => V.(ep).(V.T)  ---- 2
# also,     A * V = ep * U                                        
# We first solve for LHS i.e we calculate A.(A.T)

In [96]:
# calculate A.A.T
a2 = a@a.T # symmetric matrix
print(a2)
# we know that if 'A' is singular matrix than it's determinant is zero
# det((A.T).A - lmda*I) = 0 ? What does it means               ------ 3      
# since A.(A.T) dot product of a matrix with its transpose is identitymatrix * eigenvalue
# and we need to find eigenvalue

[[50 30]
 [30 50]]


In [97]:
# if you solve 3rd equation you get
# lmda**2 - 100*lmda + 1600 = 0
# and we have to find lmda
# (1)*lmda**2 + (-100)*lmda + 1600
roots = np.roots((1,-100,1600))

In [121]:
lmda = np.sqrt(roots) # why we take quare root because we calculate using A.(A.T) by multiplying A**2 not by A
print(lmda)

[8.94427191 4.47213595]


In [122]:
# find eigen vectors
# A.(A.T).I = eignvalue * I    {I vectors lie in a null space because it presence dont affect the result}
# we have to find I vector for both eignvalue or epsilon result is eignvector

In [123]:
a1,b1 = np.linalg.eigh((a@a.T)) # columns space eign vectors 
a2,b2 = np.linalg.eigh((a.T@a)) # row space eign vectors

In [124]:
print(b1)
print(lmda)
print(b2)

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[8.94427191 4.47213595]
[[-0.9486833   0.31622777]
 [ 0.31622777  0.9486833 ]]


In [125]:
# Now implement with svd
np.linalg.svd(a)

(array([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]]),
 array([8.94427191, 4.47213595]),
 array([[ 0.31622777,  0.9486833 ],
        [ 0.9486833 , -0.31622777]]))