# 01. Tensors and Operations

In [2]:
import tensorflow as tf

In [9]:
############################
# 1. Scaler and operations #
############################
# constant is scaler in tensorflow

d1 = tf.constant([[1,2,3],[3,2,1]]) # 1D matrix
d1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 2, 1]])>

In [10]:
d1.shape

TensorShape([2, 3])

In [12]:
d1.dtype

tf.int32

In [16]:
d1[:,:1] # Accessing 1st column like numpy


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]])>

In [25]:
d1[:,1, tf.newaxis]# If you paas tf.newaxis it will return 2d matrix

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [2]])>

In [32]:
d1 = d1 * 10
d1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[100, 200, 300],
       [300, 200, 100]])>

In [34]:
tf.square(d1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10000, 40000, 90000],
       [90000, 40000, 10000]])>

In [35]:
d1 @ tf.transpose(d1)  # This is dot product. We cannot use .T for transpose just like we did in numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140000, 100000],
       [100000, 140000]])>

In [36]:
# To calculate mean
tf.reduce_mean(d1)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [40]:
tf.reduce_mean(d1, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([200, 200, 200])>

In [41]:
tf.reduce_mean(d1, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([200, 200])>

In [42]:
############################################################################################
# Keras low level operation function: All function are the subset of tensorflow functions  #
############################################################################################
from tensorflow import keras
k = keras.backend
k.square(d1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10000, 40000, 90000],
       [90000, 40000, 10000]])>

### 1.1. Tensors and Numpy

In [43]:
# We can create the tensor from numpy as well
import numpy as np

d2 = np.array([1,2,3])
tf.constant(d2) # Convert numpy to tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [44]:
d1.numpy() # convert tensor to numpy

array([[100, 200, 300],
       [300, 200, 100]])

In [46]:
np.square(d1.numpy()) # Passing numpy matrix

array([[10000, 40000, 90000],
       [90000, 40000, 10000]], dtype=int32)

In [48]:
np.square(d1) # passing tensor object

array([[10000, 40000, 90000],
       [90000, 40000, 10000]], dtype=int32)

In [49]:
# Numpy use default 64-bit precision. While tensor use 32-bit. So when we create the tensor from numpy make sure its dtype=tf.float32

### 1.2. Type Conversion

In [50]:
# This will through an error
tf.constant([1]) + tf.constant([1.])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [59]:
tf.constant([1.]) + tf.constant([1.], dtype=tf.float64) # First tensor is float32 bit while second is float64

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

In [64]:
tf.constant([1]) + tf.cast(tf.constant([1.]), tf.int32)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>

In [63]:
# This will through an error because you are passing float data and type integer
tf.constant([1]) + tf.constant([1.], dtype=tf.int32)

TypeError: Cannot convert [1.0] to EagerTensor of dtype int32

### 1.3. Variables
tf.Tensor values are immutable we can't modify them

In [65]:
v = tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [68]:
v.assign(2*v)  # Squaring

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [86]:
v[1,1].assign(tf.cast(v[1,1]/10,tf.int32)) # Divide operation convert dtype to float so we must need to take care of that

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8,  0, 12]])>

In [89]:
v.scatter_nd_update(indices=[[0,0],[1,2]], updates=[100, 200]) # assignment on multiple indexes

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[100,   4,   6],
       [  8,   0, 200]])>

In [90]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[100,   4,   6],
       [  8,   0, 200]])>

### 1.4. Strings

In [4]:
str1 = tf.constant("My name is John")
str1

<tf.Tensor: shape=(), dtype=string, numpy=b'My name is John'>

In [7]:
str1.shape  # You will get Null shape 

TensorShape([])

In [13]:
tf.constant("café")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [17]:
u = tf.constant([ord(i) for i in "café"])
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233])>

In [29]:
b = tf.strings.unicode_encode(u, "UTF-8") # Here u is 4 int numbers
tf.strings.length(b,unit='UTF8_CHAR')


<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [30]:
tf.strings.unicode_decode(b,"UTF-8") # B is cafe string when you decode it. It return 4 int numbers.

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233])>

### 1.5. Other Data Structures

In [40]:
# String Array
p = tf.constant(["Café", "Coffee", "caffè", "咖啡"])
p

<tf.Tensor: shape=(4,), dtype=string, numpy=
array([b'Caf\xc3\xa9', b'Coffee', b'caff\xc3\xa8',
       b'\xe5\x92\x96\xe5\x95\xa1'], dtype=object)>

In [33]:
len(p)

4

In [35]:
tf.size(p)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [39]:
tf.strings.length(p, unit='UTF8_CHAR')

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 2])>

In [44]:
r = tf.strings.unicode_decode(p,"UTF8")
r

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 232], [21654, 21857]]>

### 1.6. Ragged Tensors

In [46]:
r[0]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 67,  97, 102, 233])>

In [47]:
p[0]

<tf.Tensor: shape=(), dtype=string, numpy=b'Caf\xc3\xa9'>

In [49]:
p[0:2] # Slice also a tensor

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Caf\xc3\xa9', b'Coffee'], dtype=object)>

In [54]:
tf.ragged.constant([[1,2,3],[1,2]]) # Nested list

<tf.RaggedTensor [[1, 2, 3], [1, 2]]>

In [55]:
tf.constant([[1,2,3],[1,2]]) # You cannot store non-uniform nest list using direct tf.constant

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [61]:
a = tf.ragged.constant([[1,2,3],[10,20], [55,66,77]])
b = tf.ragged.constant([[4,5,6,7,8],[45,56,67]])
tf.concat([a,b], axis=0)

<tf.RaggedTensor [[1, 2, 3], [10, 20], [55, 66, 77], [4, 5, 6, 7, 8], [45, 56, 67]]>

In [68]:
c = tf.concat([a,b], axis=0)
c

<tf.RaggedTensor [[1, 2, 3], [10, 20], [55, 66, 77], [4, 5, 6, 7, 8], [45, 56, 67]]>

In [71]:
c.to_tensor() # Tensor is a N-D matrix

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  0,  0],
       [10, 20,  0,  0,  0],
       [55, 66, 77,  0,  0],
       [ 4,  5,  6,  7,  8],
       [45, 56, 67,  0,  0]])>

### 1.7. Spare Tensor

In [72]:
s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])
s

In [73]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [80]:
tf.sparse.to_dense(s*231)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[  0., 231.,   0.,   0.],
       [462.,   0.,   0.,   0.],
       [  0.,   0.,   0., 693.]], dtype=float32)>

In [87]:
tf.sparse.to_dense(s+42.)

TypeError: unsupported operand type(s) for +: 'SparseTensor' and 'float'

In [94]:
s.shape

TensorShape([3, 4])

In [95]:
s4 = tf.constant([[10., 20.], [30., 40.], [50., 60.], [70., 80.]]) # 4*2 matrix
tf.sparse.sparse_dense_matmul(s, s4)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 30.,  40.],
       [ 20.,  40.],
       [210., 240.]], dtype=float32)>

In [96]:
# when creating a sparse tensor, values must be given in "reading
# order", or else `to_dense()` will fail.
s5 = tf.SparseTensor(indices=[[0, 2], [0, 1]],  # WRONG ORDER!
                     values=[1., 2.],
                     dense_shape=[3, 4])
try:
    tf.sparse.to_dense(s5)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

indices[1] = [0,1] is out of order. Many sparse ops require sorted indices.
    Use `tf.sparse.reorder` to create a correctly ordered copy.

 [Op:SparseToDense]


In [99]:
#shows how to fix the sparse tensor s5 by reordering its values
s6 = tf.sparse.reorder(s5)
tf.sparse.to_dense(s6)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 2., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### 1.8. Tensor Array