# 01. Tensors and Operations

In [1]:
import tensorflow as tf

In [9]:
############################
# 1. Scaler and operations #
############################
# constant is scaler in tensorflow

d1 = tf.constant([[1,2,3],[3,2,1]]) # 1D matrix
d1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 2, 1]])>

In [10]:
d1.shape

TensorShape([2, 3])

In [12]:
d1.dtype

tf.int32

In [16]:
d1[:,:1] # Accessing 1st column like numpy


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]])>

In [25]:
d1[:,1, tf.newaxis]# If you paas tf.newaxis it will return 2d matrix

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [2]])>

In [32]:
d1 = d1 * 10
d1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[100, 200, 300],
       [300, 200, 100]])>

In [34]:
tf.square(d1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10000, 40000, 90000],
       [90000, 40000, 10000]])>

In [35]:
d1 @ tf.transpose(d1)  # This is dot product. We cannot use .T for transpose just like we did in numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140000, 100000],
       [100000, 140000]])>

In [36]:
# To calculate mean
tf.reduce_mean(d1)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [40]:
tf.reduce_mean(d1, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([200, 200, 200])>

In [41]:
tf.reduce_mean(d1, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([200, 200])>

In [42]:
############################################################################################
# Keras low level operation function: All function are the subset of tensorflow functions  #
############################################################################################
from tensorflow import keras
k = keras.backend
k.square(d1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10000, 40000, 90000],
       [90000, 40000, 10000]])>

### 1.1. Tensors and Numpy

In [43]:
# We can create the tensor from numpy as well
import numpy as np

d2 = np.array([1,2,3])
tf.constant(d2) # Convert numpy to tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [44]:
d1.numpy() # convert tensor to numpy

array([[100, 200, 300],
       [300, 200, 100]])

In [46]:
np.square(d1.numpy()) # Passing numpy matrix

array([[10000, 40000, 90000],
       [90000, 40000, 10000]], dtype=int32)

In [48]:
np.square(d1) # passing tensor object

array([[10000, 40000, 90000],
       [90000, 40000, 10000]], dtype=int32)

In [49]:
# Numpy use default 64-bit precision. While tensor use 32-bit. So when we create the tensor from numpy make sure its dtype=tf.float32

### 1.2. Type Conversion

In [50]:
# This will through an error
tf.constant([1]) + tf.constant([1.])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [59]:
tf.constant([1.]) + tf.constant([1.], dtype=tf.float64) # First tensor is float32 bit while second is float64

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

In [64]:
tf.constant([1]) + tf.cast(tf.constant([1.]), tf.int32)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>

In [63]:
# This will through an error because you are passing float data and type integer
tf.constant([1]) + tf.constant([1.], dtype=tf.int32)

TypeError: Cannot convert [1.0] to EagerTensor of dtype int32

### 1.3. Variables
tf.Tensor values are immutable we can't modify them

In [65]:
v = tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [68]:
v.assign(2*v)  # Squaring

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [86]:
v[1,1].assign(tf.cast(v[1,1]/10,tf.int32)) # Divide operation convert dtype to float so we must need to take care of that

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8,  0, 12]])>

In [89]:
v.scatter_nd_update(indices=[[0,0],[1,2]], updates=[100, 200]) # assignment on multiple indexes

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[100,   4,   6],
       [  8,   0, 200]])>

In [90]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[100,   4,   6],
       [  8,   0, 200]])>

### 1.4. Strings